### ISSUE TITLE
RAWデータの読み込みエラー解決について

### ISSUE THREAD

**Issue by gottsu43** [YuukiWada/PyXRAIN#1]
RAWデータを読み込む際に、エラーが出ることがあるので、問題点と解決方法を記載する(全て、PyXRAIN/lib/PyXRAIN.pyの一部を変更することで解決できる)。

・RAWデータは、site_nameが未定義である。よって、site_idに"0000"、site_nameに"未定義"を追加することで解決できる。
・PHM0やPVM0などの受信電力(MTI処理後)を読み込む際は、type_numとobs_idの"09"を"9"に変更する。

**Comment by YuukiWada** [comment]
報告ありがとうございました。遅くなりましたが修正対応しております。
